### PR TITLE
Do not require doctests for dunder methods

### PR DESCRIPTION
**Pull request by Fongeme**
nothing much to add, part of https://github.com/TheAlgorithms/Python/pull/4352

### CODE REVIEW

**Comment by Fongeme** [comment]
i also ran my formatter, please let me know if i should revert it

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
Thanks for doing this. I completely forgot that we had a reason to not skip those dunder methods, but it makes sense to skip them. What do you say? @cclauss 

Also, what formatter did you run? It changed a few things in a not so good way lol. We use `pre-commit` so if you enable it, you can just forget about the formatting part ;)

**Comment by cclauss** [comment]
My sense is that _some_ dunder methods should be tested like `__iter__()`,  `__repr__()`,  `__str__()` because users of the class will depend on them.  So instead of a blanket statement that no dunder methods should be tested, how about an _ignore list_ of dunder methods that do not need to be tested.

**Comment by Fongeme** [comment]
Makes sense.
For that reason I'm going to ignore the following:
init (already ignored currently)
all equality and order operators: eq, le, lt, ge, gt 
As those are the ones that were mentioned on my PR
I will also revert the formatting
Are there any more dunders you would add right now or do you think we should keep it as lean as we need it?

**Comment by Fongeme** [comment]
BTW the formatter is default Pycharm

**Comment by Fongeme** [comment]
Or actually, when rethinking it, the equality methods maybe should also have docstrings 
I'll narrow down the problem we had, the methods were abstract, and abstract dunder methods may not need to be tested
Maybe we need to purify this requirement a bit more.

**Comment by cclauss** [comment]
PyCharm does not come from the Python Software Foundation but Black does.

**Comment by Fongeme** [comment]
Decided to close, this solution needs more thinking

**Pull request closed without merging**
